### ISSUE TITLE
Issue when using on windows

### ISSUE THREAD

**Issue by sambiomatters** [stevenvachon/broken-link-checker#1]
When trying to install on windows I get the following error, also fails when using as bower dependency:

npm ERR! Error: ENOENT, chmod 'C:\node_modules\broken-link-checker\bin\broken-li
nk-checker'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "broken-link-checker"
npm ERR! cwd C:\
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\node_modules\broken-link-checker\bin\broken-link-checker
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0

**Comment by stevenvachon** [comment]
Doesn't sound like an issue with this library specifically.

Try these solutions: http://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod

Closing for now. Will re-open if necessary.
