### ISSUE TITLE
Tool exits and logs no errors or warnings

### ISSUE THREAD

**Issue by dialex** [stevenvachon/broken-link-checker#100]
When I run `blc https://dialex.github.io/start-testing/`

It outputs `Getting links from: https://dialex.github.io/start-testing`.

And that's it. Stops the execution. No errors.
Am I doing something wrong?

**Comment by Cerberooo** [comment]
Thats because the Page is empty without JavaScript ;)

**Comment by dialex** [comment]
Oh... I use [docsify](https://docsify.js.org/#/) 🙁

**Comment by architchandra** [comment]
I'm also facing a similar issue on a local project but it uses the LAMP stack, so there is no JS injected stuff. Not sure why it's not working. It's working on other projects using similar technologies.

**Comment by architchandra** [comment]
The problem was in my usage. The project has robots set to `none` on my local environment. Use the `-f` flag fixed it.
