### ISSUE TITLE
Calmcard is deprecated, throws NPM warning

### ISSUE THREAD

**Issue by cgredig** [stevenvachon/broken-link-checker#103]
Calmcard has been deprecated, it is no longer maintained, even the sources on GitHub are gone. Apparently the only call to it is here:

https://github.com/stevenvachon/broken-link-checker/blob/a63e5bf2efd4abbb23d40d88f471b3f123bad93a/lib/internal/matchUrl.js#L22

It should be replaced by something else to remove the NPM deprecated warning.

**Comment by XhmikosR** [comment]
Anyone up for a PR? Maybe just use `glob` or something similar.

**Comment by stevenvachon** [comment]
Fixed in master branch.
