### ISSUE TITLE
onclick window.location links are not being picked up

### ISSUE THREAD

**Issue by neorganic** [stevenvachon/broken-link-checker#104]
<button onclick="window.location='www.some-website-url.com';" type="button" class="btn read-more-btn">

This is a valid link, but the crawler ignores this link. This should be fixed.

**Comment by stevenvachon** [comment]
This requires a JavaScript runtime.
https://github.com/stevenvachon/broken-link-checker/projects/2#card-2200507

**Comment by stevenvachon** [comment]
Closing for now as this is not currently on track to be implemented.
