### ISSUE TITLE
broken image links are not being picked up if the link is valid(but not the right type - e.g. a html link)

### ISSUE THREAD

**Issue by neorganic** [stevenvachon/broken-link-checker#105]
`<img src="https://www.summitpost.org/users/donekey/43353" alt="test" width="100" height="100">`

In this example we have a broken link due to bad type of link, but the checker doesn't pick up on this.

**Comment by stevenvachon** [comment]
Are you using [filterLevel](https://github.com/stevenvachon/broken-link-checker#optionsfilterlevel)?
