### ISSUE TITLE
Check images in responsive images `<picture><source srcset="...">`

### ISSUE THREAD

**Issue by Flimm** [stevenvachon/broken-link-checker#107]
You can create responsive images using the `<picture>` element like this:

```html
<picture>
  <source srcset="large.jpg, extralarge.jpg 2x" media="(min-width: 800px)">
  <img src="example.jpg" alt="Example">
</picture>
```

It's also possible to use the `srcset` attribute in the `<img>` element like this:

```html
<img srcset="example-320w.jpg 320w,
             example-480w.jpg 480w,
             example-800w.jpg 800w"
     sizes="(max-width: 320px) 280px,
            (max-width: 480px) 440px,
            800px"
     src="example-800w.jpg" alt="Example">
```

Currently, broken-link-checker does not check these images to see if they are valid links. It would be nice if it did. Note that the attribute `srcset` would need parsing, as it's not always just a normal URL.

**Comment by stevenvachon** [comment]
Try the v0.8 branch as `srcset` support has already been added there.

**Comment by Flimm** [comment]
That's great!

I'm trying to get 0.8 to work with `srcset`, and I can't. Here's my sample document:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>
<body>
<div>
    <picture>
        <source srcset="hello.png" type="image/webp">
        <img src="normal.png" alt="hi">
    </picture>
    <a href="http://example.com">hi</a>
    <a href="http://google.com/ueoueo/ueo">another</a>
</div>
</body>
</html>
```

And here's the result of the command I'm running:

```
$ bin/blc --filter-level 3 -r -v 'http://0.0.0.0:8000/hi.html'
Getting links from: http://0.0.0.0:8000/hi.html
├─BROKEN─ http://0.0.0.0:8000/normal.png (HTTP_404)
├───OK─── http://example.com/
```

Interestingly, the link to google.com is not working either. I'm not sure what I'm doing wrong.

**Comment by stevenvachon** [comment]
I haven't tested `srcset` values that don't contain size information. Is that valid syntax?

**Comment by Flimm** [comment]
Yes it is. See this article: https://css-tricks.com/using-webp-images/

**Comment by stevenvachon** [comment]
Okay. There might be something wrong with [parse-srcset](https://npmjs.com/parse-srcset).

**Comment by stevenvachon** [comment]
I cannot reproduce this and there's been no `parse-srcset` release since you'd first reported. I've just added tests to support this.
