### ISSUE TITLE
Test Runner/Watcher

### ISSUE THREAD

**Issue by katerberg** [stevenvachon/broken-link-checker#11]
It would be really nice to have a test runner that watches our workspace while working to give real time feedback on tests rather than having to manually re-run mocha after each change.

Something like `karma` would be ideal: http://attackofzach.com/setting-up-a-project-using-karma-with-mocha-and-chai/

https://github.com/karma-runner/karma-mocha

**Comment by stevenvachon** [comment]
Hmm, looks like a lot of setup for something that seems to merely replace the need for pressing "up" and "enter" in a terminal. Are you using WebStorm?

**Comment by katerberg** [comment]
Not using webstorm.

The set up isn't bad. I might throw up a PR for it when I get some free time and you can decide then if the complication is worth it. I find that reducing the manual steps makes me run my tests more often.
