### ISSUE TITLE
[QUESTION] How to disable page with different query parameters being crawled multiple times

### ISSUE THREAD

**Issue by neorganic** [stevenvachon/broken-link-checker#111]
How to disable same url only with different query parameters being crawled multiple times?
Ideally I would understand the urls with query parameters should still be crawled once if it's url base wasn't crawled before.

 I am sorry if this was asked before or is in the docs - couldn't find it.

![](https://i.imgur.com/1Bpv5D0.png)

**Comment by stevenvachon** [comment]
I don't know where you're getting that log from, but if you use this project's CLI, you'll see that same URLs are cached.

**Comment by neorganic** [comment]
This is just some UI I made for better viewing this packages output

**Comment by stevenvachon** [comment]
Neat. Is it public? You can use the `http.cached` property to filter redundancy.

**Comment by neorganic** [comment]
Atm no, but relatively soon it will be - if you're interested I can notify you once it's public ;)

**Comment by stevenvachon** [comment]
Yeah, sounds interesting.
