### ISSUE TITLE
Why does BLC try to access this URL?

### ISSUE THREAD

**Issue by languagedan** [stevenvachon/broken-link-checker#118]
First of all, thank you for the nice application. Very useful and enjoyable to use. 

Now, on to my issue...

BLC reported the following error:
├─BROKEN─ https://www.nobleprog.de/ocup2-training (HTTP_404)

Why does BLC try to access this URL? 

This URL:
- does not exist on my site
- does not exist in my sitemap (https://www.nobleprog.de/sitemap.xml)
- is not referenced by any internal links on https://www.nobleprog.de.

How does BLC determine what URLs to test if not through the above?

Thank you in advance

**Comment by languagedan** [comment]
Update: I've discovered that my #3 supposition above was wrong. I used three tools to search for the link...the first two (Google Webmaster Tools and Internal Link Analyzer) failed to find it. The third one (wget) found it. Problem solved.

**Comment by stevenvachon** [comment]
The CLI's log will have told you which page the broken link was found. You'd just have to search that page's HTML source for the URL; just be mindful that it may have been a relative URL, so searching may not be exact.

If you use the programmatic API, you can get the original URL as well as the element's selector and attribute name.

**Comment by languagedan** [comment]
Thanks Steven,

I was inspecting a parsed version of the log (containing only the lines with "HTTP_404" in them). The original log has the parent link right there:

Getting links from: https://www.nobleprog.de/ocup2-and-oceb2-new-omg-certifications
├─BROKEN─ https://www.nobleprog.de/ocup2-training (HTTP_404)
├─BROKEN─ https://www.nobleprog.de/oceb-training (HTTP_404)
Finished! 473 links found. 471 excluded. 2 broken.

--Daniel

**Comment by slang800** [comment]
@languagedan - this issue should be closed.

**Comment by UltraGabacho** [comment]
Dan, I've been searching for you on the internet. It's Amitai (the biodiesel guy you did a website for in Seattle in 2010).  Call me (206) 476-9596.
