### ISSUE TITLE
Doesn't follow redirects

### ISSUE THREAD

**Issue by mkantautas** [stevenvachon/broken-link-checker#119]
Links like:

http://www.youtube.com/karolinskainstitutet are marked as 404, when they actually(in the end) are redirecting to a 200 page.

Is there an option value that can be switched off? In any case, I think this should be by default as well.

**Comment by zeke** [comment]
I'm having this same problem. Did you figure it out, @neorganic?

**Comment by addisonlynch** [comment]
+1

**Comment by thiagosanches** [comment]
Guys, try to use the --get option, since I noticed that by default it does a HEAD request.

**Comment by revelt** [comment]
Strange, CLI works fine:
<img width="608" alt="cli" src="https://user-images.githubusercontent.com/8344688/58186506-f188bc00-7cac-11e9-86ac-335f8afab5df.png">

@neorganic Please update on the status of this issue. Are you still experiencing problems? If so, are you sure you set `options.requestMethod` as `get`?

**Comment by zeke** [comment]
>  try to use the --get option, since I noticed that by default it does a HEAD request. Since I started using the --get option to force a GET request it started to follow the redirects.

This CLI option worked for me.

**Comment by stevenvachon** [comment]
Is this fixed if you try master branch (unreleased v0.8)?
