### ISSUE TITLE
Add support for configuration file

### ISSUE THREAD

**Issue by trevordmiller** [stevenvachon/broken-link-checker#123]
For example, right now I have an npm script that looks like this:

```js
"broken-links": "blc http://yoursite.com -ro --exclude=linkedin.com --exclude=visualstudio.com --exclude=netflix.com --exclude=apple.com"
```

It would be nice if I could move all the config to a `.blcrc.json` configuration file like:

```js
{
  "input": "https://yoursite.com",
  "recursive": true,
  "ordered": true,
  "exclude": [
    "linkedin.com",
    "visualstudio.com",
    "netflix.com",
    "apple.com"
  ]
}
```

Then the npm script could simply be:

```js
"broken-links": "blc"
```

`cosmiconfig` is one option many other tools use (ie prettier) for this:
https://github.com/davidtheclark/cosmiconfig

**Comment by slang800** [comment]
Why not just put

```bash
blc http://example.com \
    -ro \
    --exclude=linkedin.com \
    --exclude=visualstudio.com \
    --exclude=netflix.com \
    --exclude=apple.com
```

...in a file like `link-checker.sh` and run that? That would be much better than adding a bunch of filesystem calls to look for configuration files every single time you run `blc`.
