### ISSUE TITLE
Excluding certain url extensions

### ISSUE THREAD

**Issue by loganpowell** [stevenvachon/broken-link-checker#131]
HI! So happy to have found something that works for URLs with special characters! Just one question: Is there a way to exclude certain URL extensions (e.g., `.json`)?

**Comment by loganpowell** [comment]
Sorry, didn't check `--help` :P

**Comment by Harshalrathore007** [comment]
Hello! @loganpowell 
What was the syntax you used to exclude a particular type of link from being checked.

**Comment by loganpowell** [comment]
This was years ago... Try using the `--help` utility

**Comment by Harshalrathore007** [comment]
@loganpowell i tried using it with a bunch of different syntax none worked for me till now.
