### ISSUE TITLE
Drop support for Node 4 and down?

### ISSUE THREAD

**Issue by JustinBeckwith** [stevenvachon/broken-link-checker#136]
Node.js 4 and down are all out of LTS, so you probably don't need to support those :)  Any thoughts on a PR to update supported versions and drop these?

**Comment by stevenvachon** [comment]
Use the v0.8 branch

**Comment by JustinBeckwith** [comment]
It looks like there's a lot going on in there!  If I may suggest - it's probably a lot easier to make many of these changes on master and cut a breaking release.  The big issue we're running into is that many of your dependencies are out of date, which makes installation trigger all kind of audit alerts.  I'd be happy to help contribute if that's helpful!  I'd much rather help make this shine than fork.

**Comment by stevenvachon** [comment]
The v0.8.0 branch is much needed for international URLs, so a breaking change is will happen anyway.
