### ISSUE TITLE
Improper handling of / configuration for 3xx redirect status codes

### ISSUE THREAD

**Issue by addisonlynch** [stevenvachon/broken-link-checker#140]
I understand this may have similarities to #47, #49, #119, and #78, but I wanted to see what the proper procedure is for handling redirect URLs.

Consider these simple http -> https redirects which end in a 200 response after a 307:

- http://alphalab.org/  (307 redirect to https://alphalab.org)
- http://www.innovationworks.org/ (307 redirect to https://www.innovationworks.org/)

This package reports these links as below:

![image](https://user-images.githubusercontent.com/21162161/53122364-70dae800-3524-11e9-841c-e1fcbb55aa69.png)

This should not be the correct behavior, as the links are not broken. They redirect to a different site, which returns a 200, an 'OK' status code. For most users' purposes, these links are 'OK'. 

Is there some option in this package which allows handling of these redirects differently than the default behavior? We are unable to use this checker as it is overreporting the number of broken links on our sites. 

Any help would be greatly appreciated.

Thanks!

**Comment by stevenvachon** [comment]
Does this happen with the v0.8.0 branch?

**Comment by addisonlynch** [comment]
Works now, thank you!

**Comment by ttobis** [comment]
@stevenvachon thank you for this great tool!
Question: how can I get this fix via npm? I tried: `npm install https://github.com/stevenvachon/broken-link-checker/tree/v0.7.x` but it doesn't work.

Thanks!

**Comment by stevenvachon** [comment]
@ttobis `npm run build`
