### ISSUE TITLE
No broken links found

### ISSUE THREAD

**Issue by kam11011** [stevenvachon/broken-link-checker#146]
I have installed broken link checker , as well as every other link checker available for Wordpress and they all show that my site has zero broken links. when using regular online broken link checkers I get a 50 broken links. Is there something mis-configured on my Word press blog for this to happen? I see that I am not the only person that has this problem.

Thanks!

**Comment by Cerberooo** [comment]
At least you should provide a link to test it.

**Comment by kam11011** [comment]
Do you mean to post one of the broken links into this thread?

**Comment by Cerberooo** [comment]
No I mean a page you mentioned.

**Comment by revelt** [comment]
@kam11011  Can it be robots thing, can you check please, are permissions for crawlers set to allow crawling? That's the only idea I can come up with without actual page to test..
