### ISSUE TITLE
Add option for checking only whitelisted urls

### ISSUE THREAD

**Issue by safareli** [stevenvachon/broken-link-checker#153]
**Is your feature request related to a problem? Please describe.**
Currently you can  only specify excluded keywords (and it has no regex or some advanced glob pattern support). and if you want to check links which have some specific prefix you can't. 

**Describe the solution you'd like**
Either option for whitelisted prefix/pattern should be added which when present discards everthing not having this prefix, or matching this pattern. Or use some advanced glob pattern/regex support for the `--exclude` option

**Describe alternatives you've considered**
--

**Additional context**
I wanted to run this script against a markdown file published on a github project, but this script starts to crawl commits/pulls etc, and i only cared link made in this doc folder, if i had a way to specify whitelisted url pattern i would have specified prefix like `https://github.com/stevenvachon/broken-link-checker/tree/master/docs` for example

**Comment by stevenvachon** [comment]
`--exclude` accepts `*`.

**Comment by safareli** [comment]
Excluding everything is not useful. I need to exclude everything which starts with https://github.com/stevenvachon/broken-link-checker/tree/master/docs for example. and * can't help with that.

**Comment by stevenvachon** [comment]
Added to `master` (v0.8) branch.

**Comment by safareli** [comment]
For some reason i don't see any new commits on master branch. can you link the commit has or something if it's pushed? looks like v8 is not published on npm, when are you planning to make a release?

**Comment by stevenvachon** [comment]
Commits were squashed. The changes are there. Not sure when it'll get released.
