### ISSUE TITLE
Issue with youtube urls

### ISSUE THREAD

**Issue by casaran** [stevenvachon/broken-link-checker#154]
**Bug description**
I have been testing HtmlUrlChecker on this page (but the bug is not limited to this page): https://unity.com/solutions/film-animation-cinematics and for some youtube videos, the result will look like this:

{ url:
   { original: 'urew479-Wlw',
     resolved: 'https://unity.com/solutions/urew479-Wlw',
....

And throw a 404 for a normal working youtube video.

**To Reproduce**
const blc = require('broken-link-checker');

const options = {
  excludedKeywords: [
    'https://www.linkedin.com',
    'https://linkedin.com',
  ],
  requestMethod: 'GET',
};

var htmlUrlChecker = new blc.HtmlUrlChecker(options, {
  link: function (result) {
    if (result.broken) {
      console.log(result);
      throw '';
    }
  },
});

var baseUrl = 'https://unity.com';
htmlUrlChecker.enqueue('https://unity.com/solutions/film-animation-cinematics', baseUrl);

**Expected behavior**
{ url:
   { original: 'https://www.youtube.com/embed/urew479-Wlw',
     resolved: 'https://www.youtube.com/embed/urew479-Wlw',
......

returning 200.

**Environment:**
 - Mac OS Mojave 10.14.5
 - Node.js version: 10.15.1
 - broken-link-checker version: 0.7.8

Thank you for your help.

**Comment by stevenvachon** [comment]
If you disable JavaScript and look at the URLs for those links, they are in fact just the YouTube IDs. They are, in fact, broken links.

**Comment by casaran** [comment]
You are right. Thank you for your answer.
