### ISSUE TITLE
Please don't work on the next version in the master branch

### ISSUE THREAD

**Issue by charliecalvert** [stevenvachon/broken-link-checker#155]
**Is your feature request related to a problem? Please describe.**
I read the API docs on the main page (README.md for master) of your Git repo, but they were for a version (0.8.0) that hasn't been released yet on NPM. That is **npm i broken-link-checker" gets version 7, not 8. Your example made sense, and seemed reasonable, so I couldn't figure out for quite a time why it didn't work. I eventually just guessed that your main README file must be the docs for a version that had not yet been released. So I looked for an older README and was up and running in about two minutes.

**Describe the solution you'd like**
Do your work for the next version in a branch called version_8, or the like, and merge it into master when it is ready to be released.

**Describe alternatives you've considered**
Alternatively, add text to the README.md for the master that says clearly where to look for the working docs.

**Additional context**
This is a great program and I appreciate your work. But the misdirection on how to use it cost me an hour or two.

**Comment by stevenvachon** [comment]
Why not use NPM for documentation? It represents each release, with the latest being the default.

**Comment by stevenvachon** [comment]
Closing for now.

**Comment by charliecalvert** [comment]
I agree that NPM is a good way to go, but it is common to use GitHub as well. I don't want to want to add to your work, I just felt that this was a subject worth considering.
