### ISSUE TITLE
Not all links are found

### ISSUE THREAD

**Issue by vladdu** [stevenvachon/broken-link-checker#156]
**Describe the bug**
Links are not detected if the <a> tag has rel="nofollow".

**To Reproduce**
check a web page with a nofollow link

**Expected behavior**
These links should be detected too, IMHO, maybe marked as such

**Comment by stevenvachon** [comment]
Per the [documentation](https://www.npmjs.com/package/broken-link-checker#optionshonorrobotexclusions), set `honorRobotExclusions` to `false`.

**Comment by vladdu** [comment]
Ah, I missed that. But I am using the cli and there is no option to configure that.

**Comment by stevenvachon** [comment]
`--follow`

**Comment by vladdu** [comment]
Yes, I see it now. Sorry for the noise!
