### ISSUE TITLE
Error: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by BBerastegui** [stevenvachon/broken-link-checker#159]
I was testing several sites, and I found this error on one specific example:

```bash
blc --filter-level 3 --exclude-internal -r -f -o https://[REDACTED].com
```

```
RequestError: Parse Error: Invalid header value char
```

This seems to be a known error that can be "solved": https://github.com/nodejs/node/issues/22064#issuecomment-519675190

**Environment:**
 - Environment: node:latest docker image
 - Node version: `v12.10.0`
 - broken-link-checker version: 0.8.0

**Comment by stevenvachon** [comment]
Do you encounter this issue when using the currently unreleased v0.8 (via git) ?

**Comment by stevenvachon** [comment]
Do you have a stack trace?

**Comment by stevenvachon** [comment]
From https://github.com/nodejs/node/issues/21509#issuecomment-399781487:
> The `\u0001` turns into a control character when encoded to ASCII or UTF-8 and those are rejected as a security measure. That's working as expected.
