### ISSUE TITLE
How to ignore insecure/invalid/self-signed SSL certificate ?

### ISSUE THREAD

**Issue by changuelsami** [stevenvachon/broken-link-checker#164]
My website is using a self signed certificate, so blc show this error message ! 
`Error: self signed certificate`
How can I ignore such error ?
Regards

**Environment:**
 - OS and version: Ubuntu 18.10
 - Node.js version: 10.16.1
 - broken-link-checker version: 0.7.8

**Comment by tbrek** [comment]
https://github.com/stevenvachon/broken-link-checker/issues/42

**Comment by changuelsami** [comment]
@tbrek 
thanks :)
Now I have no errors, but there are also no results : 
`$ blc https://foobar.com
Getting links for https://foobar.com
$`

**Comment by stevenvachon** [comment]
This should be fixed on master branch.
