### ISSUE TITLE
Installation Issues.

### ISSUE THREAD

**Issue by fenilshah16** [stevenvachon/broken-link-checker#195]
**How do I solve this?**

<img width="893" alt="Screenshot 2020-05-25 at 12 32 44 PM" src="https://user-images.githubusercontent.com/56188454/82787426-fd8cf800-9e83-11ea-85f1-39d43c0d8d78.png">

**Environment:**
 - OS and version: macOS Catalina 10.15.4
- Node.js version: 6.13.4

**Comment by stevenvachon** [comment]
You're installing from github instead of npm? `npm run build`

**Comment by fenilshah16** [comment]
My bad,
Worked, Thanks!❤️
