### ISSUE TITLE
On master branch it seems that blc got stuck for some websites

### ISSUE THREAD

**Issue by thiagosanches** [stevenvachon/broken-link-checker#197]
**Environment:**
 - OS and version: Linux CentOS 7
 - Node.js version: v12.14.1
 - broken-link-checker version: v0.8.0-alpha (master branch: a08abcdbec9119)

I noticed that `npm install broken-links-report` still points to the 0.7.8 version and I want to test your latest version since I noticed that you are not using the bhttp module anymore, that was causing some issues on the 0.7.8 version (#184).

I ran the following commands as soon as I cloned your repo:
`npm install`
`npm run build`
`node bin/blc https://g1.globo.com`

But it seems that it got stuck:
![image](https://user-images.githubusercontent.com/5191469/84208710-b9584500-aa8a-11ea-88ff-cbeb962df785.png)

Do you have any idea? For www.google.com I was able to run it:
![image](https://user-images.githubusercontent.com/5191469/84208755-d856d700-aa8a-11ea-8676-0c420adef67c.png)

Thanks,
Regards.

**Comment by kokarn** [comment]
I'm having the same issue

**Comment by stevenvachon** [comment]
So far, it seems like the [HTML parser](https://npmjs.com/parse5) is having difficulty parsing your document.

**Comment by stevenvachon** [comment]
I think this is the same as #185. Closing.
