### ISSUE TITLE
loading text file of links

### ISSUE THREAD

**Issue by meshungina** [stevenvachon/broken-link-checker#199]
Wondering if there is a way to load links from a file instead of url. I've noticed setting -r for recursive was throwing error (Unhandled Rejection. TypeError: Cannot assign to read only property 'response' of object '[object Object]')  so wondering if i can get around this by simply supplying all the links from a file.

**Environment:**
Ubuntu 18.04.3 LTS
nodejs v12.18.0
 - broken-link-checker version: v0.7.8

**Comment by stevenvachon** [comment]
You can use the programmatic API. You could also try the currently unreleased master branch.
