### ISSUE TITLE
npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/broken-link-checker/bin/broken-link-checker'

### ISSUE THREAD

**Issue by webjay** [stevenvachon/broken-link-checker#2]
$ npm install -g broken-link-checker
    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "broken-link-checker"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.8.3
    npm ERR! path /usr/local/lib/node_modules/broken-link-checker/bin/broken-link-checker
    npm ERR! code ENOENT
    npm ERR! errno -2

    npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/broken-link-checker/bin/broken-link-checker'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

**Comment by stevenvachon** [comment]
Sounds like you need to use `sudo` or set up your environment more correctly

**Comment by fernyherrera** [comment]
I get the same issue

**Comment by stevenvachon** [comment]
The new version has not yet been released. For now, try:
```shell
npm install -g git://github.com/stevenvachon/broken-link-checker.git
```

**Comment by fernyherrera** [comment]
Thanks it works.

**Comment by harlantwood** [comment]
This is still an issue.  For now you can put this in your `package.json` to get the head from github:

    "broken-link-checker": "stevenvachon/broken-link-checker"

@stevenvachon just want to make sure you're aware that the NPM version is totally broken.

**Comment by stevenvachon** [comment]
I'm aware. It's not [yet?] a popular library, so I did the major v0.5 work on master branch. The new version will be released sometime this month.

**Comment by harlantwood** [comment]
OK cool.  Thanks for developing open source software for all of us :smile:

**Comment by jonbgallant** [comment]
This worked for me
    npm install -g git://github.com/stevenvachon/broken-link-checker.git

**Comment by stevenvachon** [comment]
v0.5.0 released with this fixed.
