### ISSUE TITLE
Fails when response.headers['content-type'] is undefined

### ISSUE THREAD

**Issue by aaronjamesyoung** [stevenvachon/broken-link-checker#20]
On line 36 of `lib/internal/getHtmlFromUrl.js`, some filetypes (I saw it with .woff2 font files) don't come back with a content-type header, so the if conditional (indexOf) on this line fails. I worked around it as below, but it's a quick fix and I'm not positive if that's adequate.

Original code:
`if (response.headers["content-type"].indexOf("text/html") === 0)`

I modified it to:
`if (response.headers["content-type"] && response.headers["content-type"].indexOf("text/html") === 0)`

Hope this is helpful, let me know if you need anything.

**Comment by stevenvachon** [comment]
Thanks! v0.6.6 will be out in a few minutes. Not sure how to test an undefined content-type, though, especially when woff2 gets an official mime type.
