### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by gauravgandhi1315** [stevenvachon/broken-link-checker#204]
Does it allow to add proxy? I don't see any option to add proxy

https://github.com/stevenvachon/broken-link-checker/blob/e9d2e8723b9df7a24ddbadf95c4445c8014a67fe/lib/internal/requestHTTP.js#L31

Can anyone please help?

**Comment by stevenvachon** [comment]
This library will not be supporting proxies as it's a needless complication. You can either correct your firewall or use a [container to tunnel your requests](https://docs.docker.com/network/proxy/).
