### ISSUE TITLE
Use Client Side

### ISSUE THREAD

**Issue by toomanylogins** [stevenvachon/broken-link-checker#206]
I'm looking for a broken link checker for static pages local files. I can load the HTML into our embedded browser and execute the JavaScript programmatically. Would this work ?
Thanks
Paul

**Comment by stevenvachon** [comment]
Currently, no. The implementation for this is started for unreleased v0.8

**Comment by toomanylogins** [comment]
Thanks for confirming. I'll keep this on my todo list.
