### ISSUE TITLE
Twitter sniffs the user-agent and returns 400

### ISSUE THREAD

**Issue by jasikpark** [stevenvachon/broken-link-checker#210]
**Describe the bug**
I want to detect whether twitter links on my site are still valid, but twitter returns a 400 error for them because they sniff the user-agent and only respond 200 to an allowlist of browsers.

**To Reproduce**
Steps to reproduce the behavior.

<summary>
<code>blc -r https://jasik.xyz</code> - but you can honestly just run <code>curl -v https://twitter.com/calebjasik</code>
<details>
<pre><code>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.244.42.193...
* TCP_NODELAY set
* Connected to twitter.com (104.244.42.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [225 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [66 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2871 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Twitter, Inc.; OU=atla; CN=twitter.com
*  start date: Feb  6 00:00:00 2020 GMT
*  expire date: Feb  5 12:00:00 2021 GMT
*  subjectAltName: host &quot;twitter.com&quot; matched cert's &quot;twitter.com&quot;
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f9c4500ee00)
&gt; GET /calebjasik HTTP/2
&gt; Host: twitter.com
&gt; User-Agent: curl/7.64.1
&gt; Accept: */*
&gt; 
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
&lt; HTTP/2 400 
&lt; cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
&lt; content-security-policy: connect-src 'self' blob: https://*.giphy.com https://*.pscp.tv https://*.video.pscp.tv https://*.twimg.com https://api.twitter.com https://api-stream.twitter.com https://ads-api.twitter.com https://caps.twitter.com https://media.riffsy.com https://pay.twitter.com https://sentry.io https://ton.twitter.com https://twitter.com https://upload.twitter.com https://www.google-analytics.com https://app.link https://api2.branch.io https://bnc.lt https://vmap.snappytv.com https://vmapstage.snappytv.com https://vmaprel.snappytv.com https://vmap.grabyo.com https://dhdsnappytv-vh.akamaihd.net https://pdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://dwo3ckksxlb0v.cloudfront.net ; default-src 'self'; form-action 'self' https://twitter.com https://*.twitter.com; font-src 'self' https://*.twimg.com; frame-src 'self' https://twitter.com https://mobile.twitter.com https://pay.twitter.com https://cards-frame.twitter.com ; img-src 'self' blob: data: https://*.cdn.twitter.com https://ton.twitter.com https://*.twimg.com https://analytics.twitter.com https://cm.g.doubleclick.net https://www.google-analytics.com https://www.periscope.tv https://www.pscp.tv https://media.riffsy.com https://*.giphy.com https://*.pscp.tv https://prod-periscope-profile.*.amazonaws.com https://platform-lookaside.fbsbx.com https://scontent.xx.fbcdn.net https://*.googleusercontent.com; manifest-src 'self'; media-src 'self' blob: https://twitter.com https://*.twimg.com https://*.vine.co https://*.pscp.tv https://*.video.pscp.tv https://*.giphy.com https://media.riffsy.com https://dhdsnappytv-vh.akamaihd.net https://pdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://dwo3ckksxlb0v.cloudfront.net; object-src 'none'; script-src 'self' 'unsafe-inline' https://*.twimg.com   https://www.google-analytics.com https://twitter.com https://app.link  'nonce-NTI1MjExODMtMWM3Yy00NzBjLTliOWItMTY0ZmM3ZTYwODU4'; style-src 'self' 'unsafe-inline' https://*.twimg.com; worker-src 'self' blob:; report-uri https://twitter.com/i/csp_report?a=O5RXE%3D%3D%3D&amp;ro=false
&lt; content-type: text/html; charset=utf-8
&lt; cross-origin-opener-policy: same-origin
&lt; date: Sat, 09 Jan 2021 19:44:58 GMT
&lt; expiry: Tue, 31 Mar 1981 05:00:00 GMT
&lt; last-modified: Sat, 09 Jan 2021 19:44:58 GMT
&lt; pragma: no-cache
&lt; server: tsa_b
&lt; set-cookie: personalization_id=&quot;v1_U7XbBBfv3A+UQsocar+nmw==&quot;; Max-Age=63072000; Expires=Mon, 09 Jan 2023 19:44:58 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
&lt; set-cookie: guest_id=v1%3A161022149800528314; Max-Age=63072000; Expires=Mon, 09 Jan 2023 19:44:58 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
&lt; strict-transport-security: max-age=631138519
&lt; x-connection-hash: 46b8b2bce18af5e0b64bba68ccf3ba50
&lt; x-content-type-options: nosniff
&lt; x-frame-options: DENY
&lt; x-powered-by: Express
&lt; x-response-time: 21
&lt; x-xss-protection: 0
&lt; 
{ [2251 bytes data]
100  2251    0  2251    0     0   8526      0 --:--:-- --:--:-- --:--:--  8526
* Connection #0 to host twitter.com left intact
* Closing connection 0
calebjasik@Calebs-MacBook-Pro ~ % &gt;....                                                                                                                                
    .errorFooter {
      color: #657786;
      font-size: 80%;
      line-height: 1.5;
      padding: 1em 0;
    }

    .errorFooter a,
    .errorFooter a:visited {
      color: #657786;
      text-decoration: none;
      padding-right: 1em;
    }

    .errorFooter a:hover,
    .errorFooter a:active {
      text-decoration: underline;
    }
  &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
  &lt;div class=&quot;errorContainer&quot;&gt;
    &lt;img width=&quot;46&quot; height=&quot;38&quot;
      srcset=&quot;https://abs.twimg.com/errors/logo46x38.png 1x, https://abs.twimg.com/errors/logo46x38@2x.png 2x&quot;
      src=&quot;https://abs.twimg.com/errors/logo46x38.png&quot; alt=&quot;Twitter&quot; /&gt;
    &lt;h1&gt;This browser is no longer supported.&lt;/h1&gt;
    &lt;p&gt;
      Please switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.
    &lt;/p&gt;
    &lt;p class=&quot;errorButton&quot;&gt;&lt;a href=&quot;https://help.twitter.com/using-twitter/twitter-supported-browsers&quot;&gt;Help Center&lt;/a&gt;
    &lt;/p&gt;
    &lt;p class=&quot;errorFooter&quot;&gt;
      &lt;a href=&quot;https://twitter.com/tos&quot;&gt;Terms of Service&lt;/a&gt;
      &lt;a href=&quot;https://twitter.com/privacy&quot;&gt;Privacy Policy&lt;/a&gt;
      &lt;a href=&quot;https://support.twitter.com/articles/20170514&quot;&gt;Cookie Policy&lt;/a&gt;
      &lt;a href=&quot;https://legal.twitter.com/imprint&quot;&gt;Imprint&lt;/a&gt;
      &lt;a href=&quot;https://business.twitter.com/en/help/troubleshooting/how-twitter-ads-work.html&quot;&gt;Ads info&lt;/a&gt;
      &copy; 2021 Twitter, Inc.
    &lt;/p&gt;
  &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre>
</details>
</summary>

**Expected behavior**

I would expect that the link checker could actually detect whether the link works. I don't know whether this is out of scope of the commandline tool or not, I guess it's something I would have to do with the library - manually setting up the user-agent to be valid?

**Environment:**
 - OS and version: macOS 11.1
 - Node.js version: 15.5.1
 - broken-link-checker version:0.7.8

**Comment by stevenvachon** [comment]
Use the `--user-agent` CLI option.

**Comment by jasikpark** [comment]
thanks! 😅 didn't see that
