### ISSUE TITLE
BLC Scans hangs

### ISSUE THREAD

**Issue by saintmalik** [stevenvachon/broken-link-checker#228]
**Describe the bug**

So when I throw list of URLs to BLC to check for broken list, it runs and I have noticed when it  gets to some point in scanning then hangs and remains there forever except I quit it, and even when I restarts, it repeats that not for all website but few websites.

**To Reproduce**
Scan https://www.tensorflow.org/tutorials

**Expected behavior**
It scans to a certain level and hangs in there for ever except you quit it, it won't stop.

**Environment:**
 - OS: Ubuntu
 - Node.js version:
 - broken-link-checker version: Latest and Old Version

**Comment by stevenvachon** [comment]
Yes, I've seen this too and spent a few minutes looking into it but didn't find it.

**Comment by saintmalik** [comment]
> Yes, I've seen this too and spent a few minutes looking into it but didn't find it.

It means there is no way to go around this issue 👀
