### ISSUE TITLE
Linkedin link gives broken response even when it isn't

### ISSUE THREAD

**Issue by banner-prog** [stevenvachon/broken-link-checker#231]
**Describe the bug**
While searching for broken links, the LinkedIn link always gives a false-positive result. Even if it is not broken, it always gives a BROKEN result.

**To Reproduce**
Run the tool on a site that has the LinkedIn link and see that it gives 404 even if it is valid.

**Expected behavior**
Should not be giving error when it is not broken.

**Environment:**
 All latest and up to date.

**Comment by stevenvachon** [comment]
duplicate of https://github.com/stevenvachon/broken-link-checker/issues/91
