### ISSUE TITLE
Twitter broken link not detected

### ISSUE THREAD

**Issue by banner-prog** [stevenvachon/broken-link-checker#233]
Even if the Twitter link is broken, the tool is not being able to detect it and it gives 200 OK responses.

**Comment by matkoniecz** [comment]
can you get example of such link?

**Comment by banner-prog** [comment]
The tool considers the link http://twitter.com/nonexistingusername as 200 OK even if it is broken.

**Comment by matkoniecz** [comment]
Is Twitter reporting it as 200 OK? If yen, then Twitter is broken - not this tool :(

**Comment by banner-prog** [comment]
Well yeah. Twitter gives 200 OK responses to every URL or username handle. Can anything be done about this?

**Comment by matkoniecz** [comment]
1) You can try to get Twitter to respond with correct codes (not a real solution, but bugfix on Twitter side would be a proper one)

2) You can manually parse responses on sites that are deliberately lying in error codes and you want to support them

3) Maintain all such fragile code here (I bet that the author is not interested in this)

4) create separate project that gets url (maybe also HTML or fetches it on its own) and returns actual error code

**Comment by banner-prog** [comment]
Thanks!
