### ISSUE TITLE
Cant get results

### ISSUE THREAD

**Issue by emirbay** [stevenvachon/broken-link-checker#236]
**Describe the bug**
Cant get results when checking this site (made in React):

**To Reproduce**
blc - ro https://keen-wright-a25bee.netlify.app/

**Expected behavior**

**Environment:**
 - OS: Win 10 64x:
 - Node.js version: 14.15.1
 - broken-link-checker version: 0.7.8

**Comment by Nishantbhagat57** [comment]
Me too

**Comment by gauravgandhi1315** [comment]
I am seeing the same issue.

**Comment by benhammondmusic** [comment]
Is broken-link-checker supposed to be able to work with client rendered react apps? I also can't get any results running it on my page. If anyone knows what I'm missing let me know, thanks

**Comment by stevenvachon** [comment]
It does not currently support client-rendered apps; only server-rendered.

**Comment by benhammondmusic** [comment]
> It does not currently support client-rendered apps; only server-rendered.

Thanks! Makes total sense; just wanted to make sure I wasn't missing something. PS great package; once I figure out SSR for my app I'll be revisiting this.
