### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by AlbanMinassian** [stevenvachon/broken-link-checker#25]
How use blc behind a proxy.
All externals links are broken

```
Getting links from: http://localhost:8080/it/actus/articleB.html
├─BROKEN─ http://placehold.it/900x300 (HTTP_undefined)
```

Thank 
Ami44

**Comment by stevenvachon** [comment]
Yeah, I have plans to switch back to [request](https://npmjs.com/request) when the [next major version](request-next node) is released.

**Comment by ami44** [comment]
thanks

**Comment by stevenvachon** [comment]
We should keep this open for now, though. It can be closed when it's fixed.

**Comment by joelbasson-spotzer** [comment]
Any movement on this?

**Comment by stevenvachon** [comment]
Fixed on master branch.

**Comment by stevenvachon** [comment]
I'll be undoing this on master branch soon.
