### ISSUE TITLE
Error via API on checking

### ISSUE THREAD

**Issue by Purus** [stevenvachon/broken-link-checker#28]
I am getting the below error when running the code via the API.

```
Unhandled rejection Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:874:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

Looks like some proxy issue and how to overcome this..

**Comment by Purus** [comment]
The complete code that I am running is below for reference.

```
"use strict";

var blc = require("broken-link-checker");
var options = {};

var handlers =  
	{
		html: function(tree, robots, response, pageUrl)
		{
			console.log(response);
		},
		junk: function(result)
		{
			console.log(result);
		},
		link: function(result)
		{
			console.log(result);
		},
		page: function(error, pageUrl)
		{
				console.log(error.name + " : "+ error.message );
		},
		end: function()
		{
			console.log(data.total.pages);
		}
	};

var siteChecker = new blc.SiteChecker(options,handlers);

siteChecker.enqueue("https://github.com");
```

**Comment by stevenvachon** [comment]
If it's a proxy issue, then it's related to #25

**Comment by Purus** [comment]
In my case the issues are even before starting the validation. But n other
issue, prixy issue was for one is the link.

**Comment by stevenvachon** [comment]
I get no errors running your code.

**Comment by Purus** [comment]
It was due to proxy and I suggest to have friendly error message on this case as it was for that linked issue.

**Comment by stevenvachon** [comment]
I haven't done any testing with proxies yet, mainly because the request library that's used doesn't support them. `request` lib is very sloppy under the hood, so I'm waiting for the next release. Closing this for now, as we have #25 open.
