### ISSUE TITLE
Issues on fs object in Browerify

### ISSUE THREAD

**Issue by Purus** [stevenvachon/broken-link-checker#29]
When used along with Browserify, the FileSystem related methods does not work.

On the below lines:

```
errorCss = fs.readFileSync(__dirname + '/static/error.css', 'utf8');
errorHtml = fs.readFileSync(__dirname + '/static/error.html', 'utf8');
```

We get the below error:

`Uncaught TypeError: fs.readFileSync is not a function`

**Comment by stevenvachon** [comment]
This library does not use `fs` functions. If your code is throwing an error, I don't see how that has anything to do with this library.

**Comment by Purus** [comment]
The dependent module "errors" is using it and thus the error. With this,
it's not usable with browserify.

Thanks,
R.Purusothaman

**Comment by stevenvachon** [comment]
Ok, this is related to the request library that is used. This is related to #25 as well.

**Comment by Purus** [comment]
:+1:

**Comment by stevenvachon** [comment]
This library cannot ever be used in a browser, at least effectively. CORS will not allow any requests to third-party servers that lack the sufficient headers. Some day this library will work in a browser for internal links only, but that is a pretty low priority.
