### ISSUE TITLE
NPM Install does not work

### ISSUE THREAD

**Issue by Xanir** [stevenvachon/broken-link-checker#3]
It appears that NPM is using your .gitignore file in place of .npmignore
For more information see the SO thread: http://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod

I am not able to load your module with:
npm install broken-link-checker

However as the thread mentions I am able to load it with:
npm install broken-link-checker --no-bin-links

Which leads me to believe that if you check in a blank .npmignore file this issue will be resolved.

**Comment by Xanir** [comment]
Actually it appears that the reason that the NPM install is broken is because you reference the `bin` directory in the `package.json bin`. Either the code should be refactored to not use anything from `bin` or add `bin` to the files delivered.

**Comment by stevenvachon** [comment]
`bin` is used for global installs (cli); it must be there. However, there were some small issues I'd overlooked that were corrected in #4. Closing this for now. A new version (0.5) will be out soon when I finish writing a new dependency.
