### ISSUE TITLE
sub-sub-dependency punycode is not compatible with node.js < 6

### ISSUE THREAD

**Issue by scottnonnenberg** [stevenvachon/broken-link-checker#34]
`bhttp` pulls in old version of `tough-cookie`, which has a `>=` dependency. And that pulls in the latest Node.js 6+ version of `punycode`. Not sure if it's a problem for your codepaths, but with `npm` v3, this got promoted to the top level over other stuff, and webpack pulled it in, causing problems.

```
├─┬ broken-link-checker@0.7.1
│ └─┬ bhttp@1.2.1
│   └─┬ tough-cookie@0.12.1
│     └── punycode@2.0.0 
```

**Comment by stevenvachon** [comment]
bhttp will eventually be replaced; either with the new "request", "got" or a `fetch()` implementation. This is related to #25

**Comment by stevenvachon** [comment]
Support for `< 6.0` will be dropped in the next release, so closing this.
