### ISSUE TITLE
Feature Request: Broken Link URL

### ISSUE THREAD

**Issue by marcobiedermann** [stevenvachon/broken-link-checker#36]
It would be great if there would be way to get the current link, which is checked.
I got some errors in my links like `Invalid` but do not know which one is broken.

```
var blc = require('broken-link-checker');

var htmlChecker = new blc.HtmlChecker({}, {
  link: function(result) {
    if (result.broken) {
      console.log(blc[result.brokenReason]);
    }
  }
});
```

Output:
```
Invalid
Invalid
Invalid
Invalid
Invalid
Invalid
```

**Comment by stevenvachon** [comment]
Try `console.log(result)`. You could then do `console.log(result.url.resolved)`

**Comment by stevenvachon** [comment]
I have more testing to do to avoid "Unknown" errors.. but "Invalid" shouldn't happen -- "Invalid URL", perhaps.

**Comment by marcobiedermann** [comment]
@stevenvachon Thank you very much for your quick response Steven
