### ISSUE TITLE
can not run on linux

### ISSUE THREAD

**Issue by icloudsme** [stevenvachon/broken-link-checker#39]
Why I still can not run on linux, node v0.10.36 npm 1.3.6, object-assign 4.1.0, promise 3.2.1

**Comment by stevenvachon** [comment]
All of the tests pass on Linux: https://travis-ci.org/stevenvachon/broken-link-checker

**Comment by stevenvachon** [comment]
`object-assign` library does not shim `Object.prototype`. Use the `object.assign` library instead.

**Comment by stevenvachon** [comment]
https://github.com/stevenvachon/broken-link-checker/blob/master/test/utils/index.js#L12

**Comment by icloudsme** [comment]
resolved,thanks
