### ISSUE TITLE
Problems with gzipped sites?

### ISSUE THREAD

**Issue by meub** [stevenvachon/broken-link-checker#45]
I'm having issues making this work with sites on Amazon S3 with gzipped content. I get a "Finished! 0 links found." message back. Other sites without gzip work perfectly though.

Is this a known issue and are there plans to support sites that use gzip?

**Comment by stevenvachon** [comment]
It should be supported. I'll have to add tests to find out.

**Comment by meub** [comment]
Thanks for the response. I just published a test gzipped version of my personal site: http://test.alexmeub.com

Running `blc http://test.alexmeub.com` results in: 

    Getting links from: http://test.alexmeub.com/
    Finished! 0 links found.

Running `blc http://alexmeub.com` works just fine (my live non-gzipped site). So it seems gzipped sites don't work (at least if hosted on Amazon S3).

**Comment by stevenvachon** [comment]
[bhttp](https://npmjs.com/bhttp) doesn't support gzip. This is another reason to switch away from it.

**Comment by MrDys** [comment]
FWIW, I locally forked broken-link-checker and replaced bhttp with [request-promise](https://github.com/request/request-promise). I needed to be able to have cookies and gzip support. From what I can tell, it also addressed the redirects-reported-as-broken issue in #47.

**Comment by zeke** [comment]
I tried to add these tests today using a module called `broken-link-checker` AKA `blc`. This tool seemed promising at first, but I ran into an issue where redirects for URLs with trailing slashes were wrongly being reported by `blc` as 404s. Others have run into this as well, and it seems the library is no longer actively maintained: https://github.com/stevenvachon/broken-link-checker/issues/47

Next I think I'll give [`check-links`](https://github.com/transitive-bullshit/check-links#readme) a try...

**Comment by zeke** [comment]
> forked broken-link-checker and replaced bhttp with request-promise.

@MrDys I tried this but didn't have much luck. Can you share a link to your working fork?

**Comment by stevenvachon** [comment]
https://github.com/request/request/issues/3142

**Comment by stevenvachon** [comment]
Fixed i v0.8.0 branch.
