### ISSUE TITLE
Global install failed Error ENOENT

### ISSUE THREAD

**Issue by Ajmariff** [stevenvachon/broken-link-checker#5]
Hi,  
I got this error while installing your app. 

Error: ENOENT, chmod 'C:\Users\ADA-LT\AppData\Roaming\npm\node_modules\broken-link-checker\bin\broken-link-checker' 

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "broken-link-checker" "-g"
npm ERR! cwd C:\{*working_dir*}
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path C:\Users\{*user-login*}\AppData\Roaming\npm\node_modules\broken-link-checker\bin\broken-link-checker
npm ERR! code ENOENT
npm ERR! errno 34

Any idea what it does mean and how to fix it ? 
Frankly,  I am eager to try it. :)

Thanks guys for all this work. Seems promising.

**Comment by stevenvachon** [comment]
Here is the solution: https://github.com/stevenvachon/broken-link-checker/issues/2#issuecomment-100332306

Thank you

**Comment by Ajmariff** [comment]
It worked. Thanks.
