### ISSUE TITLE
Different API for HtmlChecker

### ISSUE THREAD

**Issue by alexturpin** [stevenvachon/broken-link-checker#55]
Hey folks,

Was there a particular reason why `HtmlChecker` has a different API than the rest of the checkers? By that I mean `scan` vs `enqueue` that allows custom data. I'm asking because I was trying to do HTML checking but I do need the option to pass custom data.

Cheers

**Comment by stevenvachon** [comment]
Enqueing an HTML string or stream would be a waste of memory. `scan` can be called on each succession.

**Comment by alexturpin** [comment]
Ah that makes sense. Thank you!
