### ISSUE TITLE
Exit code 1 if broken links are found

### ISSUE THREAD

**Issue by Dima4ka** [stevenvachon/broken-link-checker#57]
As of now, the tool exits with `code 0` in all scenarios.
I know, you have a recent commit fixing it, but the tool in NPM does not have that fix yet.

Have you updated the NPM package?
Or is it a problem on my side?

**Comment by stevenvachon** [comment]
A version was not released containing that fix. Instead v0.8.0 work began.

**Comment by Dima4ka** [comment]
Thank you for response!

Do you have an estimate when the version with the fix (v0.8.0) will be released?

**Comment by stevenvachon** [comment]
I have to complete [specurl](https://github.com/stevenvachon/specurl) first, then complete more v0.8 features. It could be another month.

**Comment by Dima4ka** [comment]
Thanks!

Would it be possible to release a minor version that fixes the issue?
It is a blocking factor, since the tool is useless if it "always succeeds".
I am planning to use it in my testing environment.

**Comment by stevenvachon** [comment]
Sure. v0.7.4 released.

**Comment by Dima4ka** [comment]
Thank you!
I appreciate it very much!
