### ISSUE TITLE
Feature: embed local http server to check static files

### ISSUE THREAD

**Issue by vanduynslagerp** [stevenvachon/broken-link-checker#60]
Would it be possible to add to the plugin the capacity to run a local http server to serve static files and then check the broken link ?

A command line like `blc _site -ro` could start a local server, serving the files in _site and then start the analysis. Maybe something along those lines:
```javascript
var finalhandler = require('finalhandler');
var http = require('http');
var serveStatic = require('serve-static');

var serve = serveStatic(<directory>);
var server = http.createServer(function onRequest (req, res) {
  serve(req, res, finalhandler(req, res))
})

server.listen(9001, function(){
    console.log('Server running on 9001...');
    // Call broken-link-checker on URL http://localhost:9001
});
```

Or maybe is there a way, in one command to start a local server, wait for it to be started and then start broken-link-checker ?
The problem with `node http-server _site -p 9001 & blc http://0.0.0.0:9001 -ro` is that broken-link-checker is executed before the webserver finish to startup and therefore produce an error.

**Comment by stevenvachon** [comment]
Sure, it's possible, but that's not the direction it'll be taking. Instead, it will support `file://` (#44).

**Comment by vanduynslagerp** [comment]
Thanks for the answer.
I was proposing this solution as you were mentioning in #44 that supporting file:// was more difficult than expected and you were suggesting to use a temporary local server.
I'll wait for #44 to be implemented ! Thanks !

**Comment by stevenvachon** [comment]
Yep. Until v0.8.0 is released, a local server is the only solution.
