### ISSUE TITLE
Links with Unicode characters reported as broken links

### ISSUE THREAD

**Issue by binhqd** [stevenvachon/broken-link-checker#64]
See attachment
![screenshot_2017-03-06_17-00-37](https://cloud.githubusercontent.com/assets/3197768/23605241/70b87bdc-028e-11e7-9456-caa9b7370318.png)

**Comment by stevenvachon** [comment]
Yes, I'm aware of this. [isomorphic-url](https://npmjs.com/isomorphic-url) will fix this.

**Comment by iget-master** [comment]
Some fix for this?

**Comment by stevenvachon** [comment]
It's already fixed in the v0.8 pre-release branch.

**Comment by majkinetor** [comment]
Can we get this released ?

**Comment by stevenvachon** [comment]
@majkinetor I had a hard drive issue in the fall requiring professional recovery and I'm now starting a new job search. I'll get to it as soon as I can.
