### ISSUE TITLE
[QUESTION] Excluded links during blc execution

### ISSUE THREAD

**Issue by RubyGemTSL** [stevenvachon/broken-link-checker#69]
Hi, 

Not an issue more of a question that I cannot find the answer to.

I have been spiking out BLC for a project that I am working on. However when I run via command line there seems to be many links that are ignored.

I am executing the tests like:
NODE_TLS_REJECT_UNAUTHORIZED=0 blc https://foo.com -ro 

The result is:
`Finished! 16516 links found. 15854 excluded. 50 broken.`

Is there a way to force blc to check all links?

Thanks,
Ian

**Comment by stevenvachon** [comment]
`blc --filter-level=3`
