### ISSUE TITLE
Error: Unhandled Rejection. TypeError: Cannot read property 'attrs' of undefined

### ISSUE THREAD

**Issue by mitchellknight** [stevenvachon/broken-link-checker#71]
I'm getting the following error:

```shell
Error: Unhandled Rejection. TypeError: Cannot read property 'attrs' of undefined
```

I have the latest `blc` installed. I'm trying to use `-ro` to check the entire site for broken links and other problems. Here's the command I'm using:

```shell
blc http://example.com -rov --filter-level 3 > audit.txt
```
Am I doing something wrong? Is there an "ignore errors and continue" option?

Thanks

**Comment by tylerbrownhenry** [comment]
I think I noticed this as well, I didn't add it to a pull request, but I just basically did a grep of the code for '.attr' and whatever object it was trying to reference I wrote an if undefined check for it.  There were only a handful of places where this happened.

if(typeof object !== 'undefined' && typeof object.attrs !== 'undefined') <== like that.

**Comment by stevenvachon** [comment]
What does the page you're checking look like? I can't imagine a situation where the `html` property would be `undefined`.

**Comment by tylerbrownhenry** [comment]
Sorry, I don't really remember, I just remembered seeing this bug, and that what I described was how I fixed it.  There were several places without that check, so it might have just been the object wasn't passed correctly, or not passed for some validation reason?

**Comment by quangpham** [comment]
I hit in the same issue. I've tried to check the site url https://www.emc.com/en-us/converged-infrastructure/converged-category-page.htm.

Searching for ".attrs" in the projects, I found quite a lot of them from both parse5 and broken-link-checker libs. Did you fix every single line that contains ".attrs"?

**Comment by tylerbrownhenry** [comment]
Yes, it was a number of places where I fixed it, but I imagine there is only 1 place where it was a problem.  I also kind of feel like this is a little bit of a hack rather than a solution to the problem. Meaning I don't know why attrs is ever not defined.

I wasn't super concerned about it for what I was doing, but I feel like I should note that.

**Comment by tylerbrownhenry** [comment]
FYI I'm not a maintainer of this project, I'm just following it for updates.

**Comment by quangpham** [comment]
Thank you tyler.

FYI, It seems adding the line if(typeof node.__location !== 'undefined' && typeof node.__location.attrs !== 'undefined') inside this code (under scrapeHtml.js) fix my problem
`		findLinks(rootNode, function(node, attrName, url)
		{
			if(typeof node.__location !== 'undefined' && typeof node.__location.attrs !== 'undefined') {
				link = linkObj(url);
				link.html.attrs = node.attrMap;
				link.html.attrName = attrName;
				link.html.base = preliminaries.base;
				link.html.index = links.length;
				link.html.location = node.__location.attrs[attrName];
				link.html.selector = getSelector(node);
				link.html.tag = stringifyNode(node);
				link.html.tagName = node.nodeName;
				link.html.text = getText(node);
				
				links.push(link);
			}

		});`

**Comment by tylerbrownhenry** [comment]
Yeah that's exactly what I did

**Comment by stevenvachon** [comment]
Just released v0.7.5 which I hope fixes this, but am not entirely sure.

**Comment by gburgett** [comment]
Steven, I just ran into this same issue even with v0.7.5.  Here's a test case which reproduces it:

```javascript
it("supports more invalid html structure", function()
{
	var html = '<html><head><title>title</title></head><body>';
	html += '<a href="fake1.html"><p></a>';
	html += '</body></html>';
	
	return wrapper(html).then( function(links)
	{
		expect(links).to.have.length(2);
		expect(links).to.be.like(
		[
			{
				url: { original:"fake1.html" },
				html:
				{
					selector: "html > body > a:nth-child(1)",
					tag: '<a href="fake1.html">',
					text: null
				}
			}
		]);
	});
});
```

The webpage in question was generated by Hugo with HTML like the following:

```markdown
<a href="http://test.com/link_intended_to_wrap_blockquote.html">

> A long block quote
> ...
> ...

</a>
```

The key seems to be that trailing `</a>` which gets wrapped by Hugo in a `<p></a></p>`.  The whole thing ends up like `<p><a href="#"></p><p></a></p>` but in the test case I reduced it to the minimum that reproduces the issue.

**Comment by stevenvachon** [comment]
@gburgett Thank you. I've reported it to the html parser: https://github.com/inikulin/parse5/issues/197
