### ISSUE TITLE
Support frame tag

### ISSUE THREAD

**Issue by flowersinthesand** [stevenvachon/broken-link-checker#75]
First, I admit that `frame` tag is obsolete according to https://www.w3.org/TR/html5/obsolete.html#frame and it is rarely used these days for sure. 

Unfortunately, however, javadoc still generates index.html using `frame` tag, which is a tool to generate html pages of API documentation from Java source files ─ https://docs.oracle.com/javase/8/docs/api/ and http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html

With `frame` tag support, broken-link-checker can be used to check JavaDoc as well. What do you think? (The following workaround is available though)

```
C:\Users\Donghwan>blc http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/
Getting links from: http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/

C:\Users\Donghwan>blc http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/overview-summary.html -ro
Getting links from: http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/overview-summary.html
├───OK─── http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/overview-tree.html
├───OK─── http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/deprecated-list.html
├───OK─── http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/index-all.html
├───OK─── http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/help-doc.html
├───OK─── http://cettia.io/projects/cettia-java-server/1.0.0-RC1/apidocs/index.html?overview-summary.html
...
```

**Comment by stevenvachon** [comment]
If you need this today, it's already been implemented in the v0.8.0 branch.

**Comment by flowersinthesand** [comment]
Ah, thanks, great! I should have checked that branch.

**Comment by stevenvachon** [comment]
No problem. Checking branches isn't expected. Let's keep this open for now, though, for anyone searching for the same feature before release.
