### ISSUE TITLE
Error: Unhandled Rejection. TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MansimranKaur** [stevenvachon/broken-link-checker#76]
I am getting the following error:
Error: Unhandled Rejection. TypeError: Cannot read property 'length' of undefined

I am using "blc http://example.com -ro" command.
This error doesn't come at any specific link or page rather it is shown randomly anywhere while running the site check.

What can be the possible reason for this behavior?
Thanks

**Comment by stevenvachon** [comment]
It's an internal error that I think is fixed in the v0.8.0 branch, but I don't know if that's broken now (for different reasons). Lots of work is being done elsewhere to get the new version out.

**Comment by MansimranKaur** [comment]
Thanks alot @stevenvachon for the answer. Lets keep a track for this issue till the release for resolving it.

**Comment by stevenvachon** [comment]
I'm going to close this because the original URL was both not included and probably different by now. v0.8's codebase is almost completely different now as well.
