### ISSUE TITLE
Importing broken-link-checker in an Ionic 3.5.3 project

### ISSUE THREAD

**Issue by bobdorff** [stevenvachon/broken-link-checker#80]
Attempting to use blc within an Ionic 3.5.3 project (Angular 4.1.3) and have tried several different ways of bringing it in to my components. 

I have added the package through npm and it is listed in my project's package.json file. I have attempted to import it into my components several different ways, including

`import { blc } from 'broken-link-checker'`
and
`import * as blc from 'broken-link-checker'`

I have also tried to include it through `app.module.ts`

 In every case, when I reference it in my code, I see the following error: 

`Object prototype may only be an Object or null: undefined`

Any insight into how I can include the package?
Thanks!

**Comment by stevenvachon** [comment]
This project cannot be made to work in a browser.
