### ISSUE TITLE
How to list only broken sites?

### ISSUE THREAD

**Issue by rybarova** [stevenvachon/broken-link-checker#81]
Hello,
how to list only broken sites? Without OK status. Or how to copy all results in clipboard to import in my TXT file. Thank you for your time.

**Comment by stevenvachon** [comment]
Not currently supported. Logging may be a feature added to v0.8, but it all depends on how much free time I have.

**Comment by rybarova** [comment]
Thank you for fast reply. So isn't possible remove or filter out all OK pages from list of broken links at this time?

**Comment by stevenvachon** [comment]
You can create your own report or log using the programmatic API.

**Comment by YPCrumble** [comment]
A simple workaround is to do something like `blc https://some-url.com | grep BROKEN | tee 2>&1 output.txt` and then you can reformat output.txt however you want.

**Comment by FelixZilber** [comment]
@rybarova check this [PR](https://github.com/stevenvachon/broken-link-checker/pull/113)
