### ISSUE TITLE
Not getting links from javascript frontend

### ISSUE THREAD

**Issue by YPCrumble** [stevenvachon/broken-link-checker#86]
Thanks for building this great library!

It appears that sites like Medium that use a javascript frontend won't get scraped by this checker. See for instance [this post](https://medium.com/the-mission/50-websites-to-post-your-product-or-your-startup-a6680ab178a6) which has many external links. The output I get is:

```
$ blc https://medium.com/the-mission/50-websites-to-post-your-product-or-your-startup-a6680ab178a6
Getting links from: https://medium.com/the-mission/50-websites-to-post-your-product-or-your-startup-a6680ab178a6
├───OK─── https://twitter.com/TheMissionT
├───OK─── https://medium.com/
├───OK─── https://facebook.com/TheMissionInc
├───OK─── https://medium.com/the-mission?source=logo-lo_dafe4ec1b540---b230ea2a6eb8
├───OK─── https://cdn-images-1.medium.com/letterbox/346/72/50/50/1*EfWc2jdGY89opF70Aa1h3Q.png?source=logoAvatar-lo_dafe4ec1b540---b230ea2a6eb8
├───OK─── https://medium.com/m/signin?redirect=https%3A%2F%2Fmedium.com%2Fthe-mission%2F50-websites-to-post-your-product-or-your-startup-a6680ab178a6&source=--------------------------nav_reg
├───OK─── https://medium.com/the-mission
├───OK─── https://medium.com/the-mission/tagged/life
├───OK─── https://medium.com/the-mission/tagged/tech
├───OK─── https://medium.com/the-mission/tagged/health
├───OK─── https://medium.com/the-mission/tagged/science
├───OK─── https://medium.com/the-mission/why-and-how-to-sponsor-branded-content-cd0e44034084
├───OK─── https://medium.com/the-mission/how-to-find-your-mission-and-success-f24b9cd69fcb
├───OK─── https://medium.com/the-mission/tagged/themissionletters
├───OK─── https://medium.com/the-mission/search
├───OK─── https://medium.com/@duplikey?source=post_header_lockup
├───OK─── https://cdn-images-1.medium.com/fit/c/120/120/1*OCy5BMqbZxsXhufdKxyHuw.jpeg
├───OK─── https://cdn-images-1.medium.com/max/2000/1*hotTfrXFovESzLWbQzDX7w.jpeg
├───OK─── https://cdn-images-1.medium.com/max/1200/1*S0H89POj_i2ndJSRFebGtg.png
├───OK─── https://cdn-images-1.medium.com/max/1200/1*Rp4dAQfFd6Oex9_DzSH_YA.png
├───OK─── https://medium.com/the-mission/how-i-wrote-a-successful-post-on-medium-2f24cde0a026
├───OK─── https://medium.com/tag/startup?source=post
├───OK─── https://medium.com/tag/startup-marketing?source=post
├───OK─── https://medium.com/tag/product-development?source=post
├───OK─── https://medium.com/@duplikey?source=footer_card
├───OK─── https://medium.com/@duplikey
├───OK─── https://medium.com/the-mission?source=footer_card
├───OK─── https://cdn-images-1.medium.com/fit/c/120/120/1*k26odIc_0das5PnOHoOtEw.png
├───OK─── https://cdn-images-1.medium.com/fit/c/80/80/1*k26odIc_0das5PnOHoOtEw.png
```
I can see the link in the frontend file, but when I try `blc --filter-level=2` to include the script in my search it doesn't include the links either. Is that expected behavior?

My suggestion would be to create a way to parse javascript files for links in javascript frontends and either include this in the --filter-level=2 or perhaps include a new flag for including these links. Let me know if I'm looking at this wrong? Happy to help with a PR if that's helpful as well. Thanks again for building this!

**Comment by stevenvachon** [comment]
`--filter-level=2` searches the values of URL *attributes* on the `<script>` element, not the script itself. Parsing the script would be lunacy for a project like this with far too many edge cases. It's a much better solution to run the scraper through something with a DOM, so that it can get dynamically added links. This feature won't be implemented for a while, though.

**Comment by YPCrumble** [comment]
@stevenvachon just so I understand you're suggesting a headless browser to actually evaluate the javascript rather than simply parsing it for links would be better? My thought was simply parse the javascript file using a regex for URLs like [one of the answers to this question](https://stackoverflow.com/q/161738/2532070). There might be a few cases way on the edge but for the most part wouldn't the regex handle the edge cases for you?

**Comment by stevenvachon** [comment]
Parsing JavaScript with a regular expression is a terrible terrible idea. A headless browser or [jsdom](https://npmjs.com/jsdom) is ideal.

**Comment by YPCrumble** [comment]
@stevenvachon in the spirit of helping someone understand why his idea is terrible, could you let me know why it's such a bad idea to parse a JS file with a regex?

**Comment by stevenvachon** [comment]
The same reason that you don't parse HTML with a regular expression: the input is so complex that it requires a tokenizer. Regular expressions exist for parsing literal strings, not source code. Research "esprima".

**Comment by YPCrumble** [comment]
Will look into that more, thank you!
