### ISSUE TITLE
[Question] Can you give some example usage of Programmatic API ?

### ISSUE THREAD

**Issue by neorganic** [stevenvachon/broken-link-checker#87]
Hello, I am having a hard time making it to work on Programmatic API - was getting undefined options, undefined html... stopped calling them in methods, but now I get 0 in terminal, but not sure or it's because the page has no broken links or I am using it wrong. Here is my code.

```
pageUrl = 'www.website.com';
const blc = require('broken-link-checker');
let htmlUrlChecker = new blc.HtmlUrlChecker( {
    html: function(tree, robots, response, pageUrl, customData){},
    junk: function(result, customData){},
    link: function(result, customData){},
    page: function(error, pageUrl, customData){},
    end: function(){}
});

log =htmlUrlChecker.enqueue(pageUrl);
console.log(log);
```

Any real live working example would be great!. Thanks in advance!

**Comment by stevenvachon** [comment]
I'm not going to answer this one. All you did was copy suggestive code from the documentation instead of comprehending it. I'm not here to teach programming nor JavaScript.

**Comment by neorganic** [comment]
Hello I am using ubuntu 16.04 LTS node v8.2.1
```
 blc https://httpstat.us/404 -ro
Getting links from: https://httpstat.us/404
Error: HTML could not be retrieved   
```
The global blc works as expected .
But I can't recreate the same results on the programmatic API :
in terminal:
`node  broken_checker.js`
which contains:
```
siteUrl = 'https://httpstat.us/404';
const blc = require('broken-link-checker');
    siteChecker = new blc.SiteChecker();
    result = siteChecker.enqueue(siteUrl);
console.log(result);   // returns 0
```
returns 0 and then closes, anyone can explain  me what I am doing wrong here?

**Comment by stevenvachon** [comment]
You have no event listeners. It's a streaming API.
