### ISSUE TITLE
External Links to LinkedIn repeatedly fail

### ISSUE THREAD

**Issue by benjaminmodayil** [stevenvachon/broken-link-checker#91]
The tool works great except on external links to LinkedIn. Every other outbound/social media link would be checked and marked appropriately except those going to LinkedIn. The LinkedIn links were not broken.

![screen shot 2017-12-15 at 6 39 06 pm](https://user-images.githubusercontent.com/12306850/34064552-dba58ec6-e1c7-11e7-8794-bcbac7aa5006.png)

After doing a search on just "HTTP-999", all the search links pointed to LinkedIn doing some blocking on requests. Here's a StackOverflow article I found.

https://stackoverflow.com/questions/27571419/how-to-avoid-http-1-1-999-request-denied-response-from-linkedin

**Comment by stevenvachon** [comment]
Yes, I'm aware of this but not sure what to do about it. Have you tried the `--user-agent` option?

**Comment by rmoriz** [comment]
Looks like LinkedIn matches by user agent, source IP address and HTTP request headers. We've added linkedin to the `--exclude` list.
