### ISSUE TITLE
urls are crawled several times within a single run

### ISSUE THREAD

**Issue by staabm** [stevenvachon/broken-link-checker#93]
when I run `blc` against mit domain with `--follow --ordered --recursive` links which are part of the layout (and therefore occur on every content-page beeing crawled) will be re-requested over and over again.

-> i see the same urls reported as broken `HTTP_404` several times within a single run

should the blc dont re-request pages which it already visited while running? I dont think it should as it wastes resources and its not likely to get a different result on a second/third call...

**Comment by stevenvachon** [comment]
Do you have evidence of the URLs being re-requested? Just because the same URL is logged multiple times does not mean that it was re-requested, it could simply mean that its cached value was re-logged because the link existed more than once.

**Comment by staabm** [comment]
the only evidence I have is that the `blc` outputs things like

```
├─BROKEN─ https://www.example.org/shop/de/infocenter/bestellservice/lieferzeiten.htm (HTTP_404)
├─BROKEN─ https://www.example.org/de/datenschutz/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/kontakt/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/konto/bestellungen/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/bewertungen/ (HTTP_404)
├─BROKEN─ https://www.example.org/blog (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/newsletter/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/impressum/ (HTTP_404)
├─BROKEN─ https://www.example.org/de/datenschutz/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/agb/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/widerrufsrecht/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/kontakt/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/newsletter/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/warenkob/liste/ (HTTP_404)
├─BROKEN─ https://www.example.org/de/services/ (HTTP_404)
├─BROKEN─ https://www.example.org/de/gewerbekunden/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/sale/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/neu/ (HTTP_404)
├─BROKEN─ https://www.example.org/de/unternehmen/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/kontakt/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/newsletter/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/infocenter/bestellservice/lieferzeiten.htm (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/kontakt/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/konto/bestellungen/ (HTTP_404)
├─BROKEN─ https://www.example.org/shop/de/faq/ (HTTP_404)

```

and since it takes ages to crawl my site, I guess that this urls would be re-retrieved over and over again

**Comment by stevenvachon** [comment]
That's just a log, and URLs are likely not being re-requested. If you want to increase the speed of the process, increase the concurrency, but you risk getting false positives.

**Comment by staabm** [comment]
how to increase the concurrency with the cli tool?

**Comment by stevenvachon** [comment]
Currently cannot via the CLI.

**Comment by staabm** [comment]
would you accept a PR adding this option?

**Comment by stevenvachon** [comment]
I might if it makes good sense.

**Comment by staabm** [comment]
cool, lets see https://github.com/stevenvachon/broken-link-checker/pull/94
