### ISSUE TITLE
Save report as HTML via CLI

### ISSUE THREAD

**Issue by webdevsuperfast** [stevenvachon/broken-link-checker#96]
@stevenvachon awesome tool, is there any way to save the report as HTML file via CLI? Thanks!

**Comment by stevenvachon** [comment]
Not currently, but you can create your own using the programmatic API.

**Comment by webdevsuperfast** [comment]
Is there any plans of adding it on future releases? I'll check on the API for now.

**Comment by stevenvachon** [comment]
No, but there're plans for a JSON export and a plugin architecture.

**Comment by webdevsuperfast** [comment]
Thanks! JSON export seems great, looking forward to it.
